import requests

username = "umutsaglam"
token = ""

projeler = [
    "amass",
    "android-security-awesome",
    "API-Security-Checklist",
    "AutoSploit",
    "awesome-appsec",
    "awesome-bug-bounty",
    "Awesome-Bugbounty-Writeups",
    "awesome-cryptography",
    "awesome-ctf",
    "awesome-cyber-skills",
    "awesome-cybersecurity-blueteam",
    "awesome-devsecops",
    "awesome-forensics",
    "Awesome-Hacking",
    "Awesome-Hacking-Resources",
    "awesome-honeypots",
    "awesome-incident-response",
    "awesome-infosec",
    "awesome-lockpicking",
    "awesome-malware-analysis",
    "awesome-ml-for-cybersecurity",
    "awesome-osint",
    "awesome-pentest",
    "awesome-pentest-cheat-sheets",
    "awesome-php",
    "Awesome-Red-Teaming",
    "awesome-reversing",
    "awesome-security",
    "awesome-shell",
    "awesome-social-engineering",
    "awesome-threat-intelligence",
    "awesome-web-hacking",
    "awesome-web-security",
    "awesome-zsh-plugins",
    "bash-it",
    "BCHackTool",
    "Beginner-Network-Pentesting",
    "binwalk",
    "botnets",
    "Brute_Force",
    "bug-bounty-reference",
    "CMSeeK",
    "commando-vm",
    "commix",
    "Covenant",
    "CrackMapExec",
    "CTF-CheatSheet",
    "CTF-tool",
    "ctf-tools",
    "ctftool",
    "cve",
    "dalfox",
    "datasploit",
    "DeathStar",
    "Depix",
    "Detect-It-Easy",
    "dirsearch",
    "dnSpy",
    "dnsrecon",
    "Dshell",
    "evilginx2",
    "EyeWitness",
    "faraday",
    "fluxion",
    "fnky",
    "free-programming-books",
    "fuzzdb",
    "fzf",
    "ghidra",
    "gobuster",
    "h4cker",
    "hacker-roadmap",
    "hacker101",
    "hacking",
    "hackingtool",
    "HackTools",
    "hacktricks",
    "Hash-Buster",
    "HiddenEye",
    "impacket",
    "Infosec_Reference",
    "instaBrute",
    "Instagram-Hacker",
    "Instagram-Phishing",
    "Inveigh",
    "joomscan",
    "king-phisher",
    "LaZagne",
    "LFISuite",
    "LinEnum",
    "linux-kernel-exploitation",
    "Linux_Exploit_Suggester",
    "MailSniper",
    "MalwareSourceCode",
    "masscan",
    "merlin",
    "mimikatz",
    "MITMf",
    "Mobile-Security-Framework-MobSF",
    "Modlishka",
    "netzob",
    "nginx-proxy",
    "nnn",
    "NoSQLMap",
    "Notepad",
    "nuclei",
    "onionscan",
    "Osintgram",
    "payloads",
    "PayloadsAllTheThings",
    "pentest-wiki",
    "PENTESTING-BIBLE",
    "personal-security-checklist",
    "phoneinfoga",
    "Photon",
    "powerlevel10k",
    "PowerSploit",
    "Probable-Wordlists",
    "ptf",
    "public-pentesting-reports",
    "pwnagotchi",
    "pwndbg",
    "pwntools",
    "python-cheatsheet",
    "python-pentest-tools",
    "radare2",
    "ranger",
    "recon-ng",
    "Responder",
    "routersploit",
    "RsaCtfTool",
    "Rubeus",
    "sec-pentesting-toolkit",
    "SecLists",
    "security-cheatsheets",
    "Security_list",
    "siber-guvenlik-sss",
    "siunam321.github.io",
    "Sn1per",
    "SocialFish",
    "social_mapper",
    "spiderfoot",
    "spycam",
    "sterraxcyl",
    "Sublist3r",
    "testssl.sh",
    "thc-hydra",
    "theHarvester",
    "ThreatHunter-Playbook",
    "tmux",
    "toutatis",
    "tplmap",
    "tsunami-security-scanner",
    "unicorn",
    "voltron",
    "vuls",
    "w3af",
    "wafw00f",
    "weevely3",
    "wifiphisher",
    "wifite",
    "Windows-Exploit-Suggester",
    "WinPwn",
    "www-project-top-ten",
    "xray",
    "XSStrike",
    "z",

]

headers = {
    "Authorization": f"token {token}",
    "Accept": "application/vnd.github.v3+json"
}

for proje in projeler:
    url = f"https://api.github.com/repos/{username}/{proje}"
    response = requests.delete(url, headers=headers)

    if response.status_code == 204:
        print(f"{proje} silindi.")
    else:
        print(f"{proje} silinirken bir hata oluştu. Hata kodu: {response.status_code}")
